Show created tasks and allow user to create a new task
karmelp/todo pull request #1
Opened 2022-09-15 13:09 UTC by karmelp

2022-09-15 13:19 UTC, hhabakuk requested changes
Hetkel oled taski lisamise teinud nii, et paned inputi sisu otse HTMLi. Kaval, see töötab, aga selline otsejoones lähenemine ei lase hästi näiteks kuvada üleval dünaamiliselt, et mitu taski on kokku ja mitu taski on tehtud. 

Seetõttu võiksid läheneda nii, et HTMLis kuvad ainult  tasks [tasks](https://github.com/karmelp/todo/blob/cdbe4ec6532b1daaa19e8c9068a4d982bf5f1d39/script.js#L3) arrayd. See tähendab, et kui klikid lisamisnupul, et süsti inputi väärtust kohe HTMLi, vaid süstid inputi väärtuse tasks arraysse ning käivitad uuesti [tasks.forEach](https://github.com/karmelp/todo/blob/cdbe4ec6532b1daaa19e8c9068a4d982bf5f1d39/script.js#L24) funktsiooni. 

Niimoodi lähenedes on taskide kustutamine ja uuendamine juba palju lihtsam!

2022-09-15 13:19 UTC, hhabakuk commented on script.js
> +        const allTasksLabelValueNumber = document.createTextNode(3);
see peaks olema dünaamiline - ära kirjuta "3", vaid kirjuta, kui palju taske kokku tegelikult on

2022-09-15 13:19 UTC, hhabakuk commented on script.js
> +        const doneTasksLabelValueNumber = document.createTextNode(2);
Sama, mis üleval, number peaks olema dünaamiline.

2022-09-15 13:19 UTC, hhabakuk commented on script.js
> +            if(document.querySelector('.newTaskField input').value.length == 0){
väga hea UX! 🥳

2022-09-15 13:19 UTC, hhabakuk commented on script.js
> +            }
siin oleks hea UX kui tühjendaksid pärast nupule klikkimist inputi ära ka

2022-09-15 13:23 UTC, karmelp commented on script.js
> +        const allTasksLabelValueNumber = document.createTextNode(3);
jaa, aga sa ütlesid ju mock teha?

2022-09-15 13:25 UTC, hhabakuk commented on script.js
> +        const allTasksLabelValueNumber = document.createTextNode(3);
jepp, mock on hea faas, et sa ei peaks kogu funktsionaalsuse peale korraga mõtlema. Nüüd oled läbi mõelnud, kuidas kuvada taske, kuidas kuvada numbreid ning ongi õige hetk mock välja vahetada dünaamilise info vastu.

2022-09-15 13:40 UTC, karmelp commented on script.js
> +            }
done

2022-09-15 13:40 UTC, karmelp commented on script.js
> +            if(document.querySelector('.newTaskField input').value.length == 0){
mina tänab

2022-09-15 14:23 UTC, karmelp commented on script.js
> +        const allTasksLabelValueNumber = document.createTextNode(3);
vist essa tehtud - pushisin input value arraysse

2022-09-16 13:24 UTC, hhabakuk commented on index.html
> +                            <span class="labelValue allTasksLabelValue"></span>
alltasksLabelValuest parema kirjeldusega oleks allTasksCount

2022-09-16 13:24 UTC, hhabakuk commented on index.html
> +                            <span class="labelValue doneTasksLabelValue"></span>
doneTasksLabelValuest parema kirjeldusega oleks doneTasksCount

2022-09-16 13:27 UTC, hhabakuk commented on script.js
> +    const taskPreviewEl = document.createElement('div')
`taskListContainerEl` on parem nimetus, taskPreviewEl indikeerib, et see on ühe ülesande eelvaate element.

2022-09-16 13:29 UTC, hhabakuk commented on script.js
> +    const taskPreviewEl = document.createElement('div')
a ei. sain nüüd aru mis see on. see on ühe ülesande konteiner ehk parem nimetuson `taskEl`

2022-09-16 13:32 UTC, hhabakuk commented on script.js
> +function showTask(task) {
show task teeb:
1. loob taski konteineri
2. täidab  taski konteineri
3. kuvab taski konteinerit taskListEl sees

2022-09-16 13:34 UTC, hhabakuk commented on script.js
> +        taskListEl.appendChild(taskListItemEl)
see kood teeb väga suures osas sama, mis showTask funktisioon


1. loob taski konteineri
2. täidab  taski konteineri
3. kuvab taski konteinerit taskListEl sees

Arenduses on konseptsioon DRY - Dont Repeat Yourself. Seega on vaja nüüd leida ühisosa, kirjutada sellest funkstioon ning kasutada seda funkstiooni mõlemas kohas.

2022-09-16 13:40 UTC, hhabakuk commented on script.js
> +        taskListEl.appendChild(taskListItemEl)
tegelikult,  kui kasutaja klikib "add new task" siis võiks juhtuda hoopis see, et teed 
```
tasks.push({title: taskTitle, isDone: 'done'})
showNumberofAllTasks();
showAllTasks();
```

kus `showAllTasks` oleks

```
const showAllTasks = tasks.forEach(task => {
    showTask(task)
});
```

Sest kui oled pushinud taski nimekirja uue taski, ei pea sa seda sama taski ise hakkama HTMLi toppima kui showAllTasks juba teeb selle ära uuendatud taskinimekirjaga.

2022-09-16 13:54 UTC, hhabakuk commented on script.js
> +});
asenda need kolm rida nii: 

```
const showAllTasks = tasks.forEach(task => {
    showTask(task)
});

```

seejärel kutsu äsjakirjutatud funktsioon järgmisel real välja: 

```
showAllTasks()
```

2022-09-16 14:03 UTC, hhabakuk commented on script.js
> +        taskListEl.appendChild(taskListItemEl)
kustuta need read ära ja kirjuta showAllTasks()

2022-09-16 14:03 UTC, hhabakuk commented on script.js
> +    const btn = document.getElementById('newTaskInput').value = ''
võta const btn eest ära ja kirjuta lihstalt

`document.getElementById('newTaskInput').value = ''`

2022-09-16 14:10 UTC, hhabakuk commented on script.js
> +});
```
const showAllTasks = () => {
  const taskListEl = document.querySelector(".taskList");
  taskListEl.innerHTML = "";

  tasks.forEach((task) => {
    showTask(task);
  });
};
```

2022-09-16 14:12 UTC, hhabakuk commented on script.js
> +        // võta newTaskField input väärtus
kustuta kõik need read

2022-09-16 14:14 UTC, hhabakuk commented on script.js
> +    p.setAttribute('class', 'allTasksCountNumber');
kustuta need read, sa ei kasuta p-d "allTasksCountNumber" klassiga kusagil

2022-09-16 14:37 UTC, merged